image:
  tag: 372

additionalCatalogs:
  delta-lake: |
    connector.name=delta_lake
    hive.metastore.uri=thrift://my-hive-metastore:9083
    hive.s3.aws-access-key=admin
    hive.s3.aws-secret-key=admin123
    hive.s3.endpoint=https://minio.minio.svc.cluster.local:9000
    hive.s3.path-style-access=true
    hive.s3.max-connections=1000
    delta.enable-non-concurrent-writes=true
  minio: |
    connector.name=hive-hadoop2
    hive.metastore.uri=thrift://my-hive-metastore:9083
    hive.s3.path-style-access=true
    hive.s3.endpoint=http://minio.minio.svc.cluster.local:9000
    hive.s3.aws-access-key=admin
    hive.s3.aws-secret-key=admin123
    hive.non-managed-table-writes-enabled=true
    hive.s3select-pushdown.enabled=true
    hive.storage-format=ORC
    hive.allow-drop-table=true
    hive.s3.ssl.enabled=false


secretMounts:
  - name: redis-table-schema-volumn
    path: /etc/redis
    secretName: redis-table-definition
