apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "trino.catalog" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: catalogs
    {{- if .Values.commonLabels }}
    {{- tpl (toYaml .Values.commonLabels) . | nindent 4 }}
    {{- end }}
data:
  delta_lake.properties: |
    connector.name=delta_lake
    hive.metastore.uri=thrift://10.111.0.11:9083
    hive.s3.aws-access-key={{ .Values.s3.user }}
    hive.s3.aws-secret-key={{ .Values.s3.password }}
    hive.s3.path-style-access=true
    delta.register-table-procedure.enabled=true

  hive.properties: |
    connector.name=hive
    hive.metastore.uri=thrift://10.111.0.11:9083
    hive.s3.path-style-access=true
    hive.s3.aws-access-key={{ .Values.s3.user }}
    hive.s3.aws-secret-key={{ .Values.s3.password }}
    hive.non-managed-table-writes-enabled=true
  tpch.properties: |
    connector.name=tpch
    tpch.splits-per-node=4
  tpcds.properties: |
    connector.name=tpcds
    tpcds.splits-per-node=4
{{- range $catalogName, $catalogProperties := .Values.additionalCatalogs }}
  {{ $catalogName }}.properties: |
    {{- $catalogProperties | nindent 4 }}
{{- end }}


