apiVersion: v1
kind: Service
metadata:
  labels:
    app: hive
  name: hive-service
  namespace: {{ .Values.global.namespace }}
spec:
  clusterIP: {{ .Values.hive.ip }}
  ports:
    - name: "hive-metastore-port"
      port: {{ .Values.hive.port }}
      targetPort: 9083
  selector:
    app: hive