apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hive
  name: hive
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive
  template:
    metadata:
      labels:
        io.kompose.network/datapipeline: "true"
        app: hive
    spec:
      {{if .Values.hive.nodeSelector }}
      nodeSelector: {{.Values.hive.nodeSelector | toYaml | nindent 8 }}
      {{end}}
      {{if .Values.hive.tolerations }}
      tolerations: {{.Values.hive.tolerations | toYaml | nindent 8 }}
      {{end}}
      containers:
      - image: {{printf "%s/%s:%s" .Values.hive.image.registry .Values.hive.image.repository .Values.hive.image.tag}}
        name: hive-metastore
        ports:
          - containerPort: 9083
        env:
        - name: HIVE_METASTORE_IP
          value: {{.Values.hive.ip | quote}}
        - name: HIVE_METASTORE_PORT
          value: {{.Values.hive.port | quote}}
        - name: S3_USER
          valueFrom:
            secretKeyRef:
              key: S3_USER
              name: trino-config
        - name: S3_PASSWORD
          valueFrom:
            secretKeyRef:
              key: S3_PASSWORD
              name: trino-config
        - name: POSTGRES_DB_IP
          valueFrom:
            secretKeyRef:
              key: POSTGRES_DB_IP
              name: trino-config
        - name: POSTGRES_DB_PORT
          valueFrom:
            secretKeyRef:
              key: POSTGRES_DB_PORT
              name: trino-config
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: trino-config
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: trino-config
        volumeMounts:
          - name: hive-log4j2-config-volume
            mountPath: /opt/apache-hive-metastore-3.0.0-bin/conf/metastore-log4j2.properties
            subPath: metastore-log4j2.properties
      volumes:
        - name: hive-log4j2-config-volume
          configMap:
            name: hive-log4j2-config
            items:
              - key: metastore-log4j2.properties
                path: metastore-log4j2.properties
      restartPolicy: Always