#FROM kubeflow/spark-operator:v1beta2-1.6.0-3.5.0
#
#USER root:root
#WORKDIR /app
#RUN mkdir -p /app
#
#COPY ./requirements.txt ./
#RUN pip3 install -r requirements.txt
#COPY ./spark/  /app/spark
#
#ENTRYPOINT [ "/opt/entrypoint.sh" ]

