silver:
  target: dev
  outputs:
    dev:
      type: trino
      user: admin
      host: http://146.190.107.105 
      port: 31088
      database: delta
      schema: silver
      threads: 1

gold:
  target: dev
  outputs:
    dev:
      type: trino
      user: admin
      host: http://146.190.107.105 
      port: 31088
      database: delta
      schema: gold
      threads: 1
      
bronze:
  target: dev
  outputs:
    dev:
      type: trino
      user: admin
      host: http://146.190.107.105 
      port: 31088
      database: delta
      schema: bronze
      threads: 1