silver:
  target: dev
  outputs:
    dev:
      type: trino
      user: admin
      host: http://206.189.92.103 
      port: 30088
      database: delta
      schema: 'silver'
      threads: 1

gold:
  target: dev
  outputs:
    dev:
      type: trino
      user: admin
      host: http://146.190.87.26 
      port: 30088
      database: delta
      schema: 'gold'
      threads: 1