conf:
  hiveSite:
    hive.metastore.uris: thrift://my-hive-metastore:9083
    javax.jdo.option.ConnectionDriverName: org.postgresql.Driver
    javax.jdo.option.ConnectionURL: jdbc:postgresql://hive-metastore-postgresql:5432/metastore_db
    javax.jdo.option.ConnectionUserName: admin
    javax.jdo.option.ConnectionPassword: admin

    fs.defaultFS: s3a://minio.minio.svc.cluster.local:9000
    fs.s3a.connection.ssl.enabled: false
    fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
    fs.s3a.endpoint: http://minio.minio.svc.cluster.local:9000
    fs.s3a.access.key: admin
    fs.s3a.secret.key: admin123
    fs.s3a.path.style.access: true

hiveMetastoreDb:
  host: hive-metastore-postgresql
  port: 5432
