version: 2

models:
  - name: fhvhv_trip
    description: Fhvhv Trip Data
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('gold', 'fact_fhvhv_trip_t')
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('bronze', 'fhvhv_tripdata')
      - dbt_expectations.expect_table_column_count_to_equal:
          value: 32
    columns:
      - name: id
        tests:
          - not_null
      - name: pickup_datetime
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: totals_amount
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: decimal
      - name: fare_per_min
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double
      - name: differ_pay_proportion
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: decimal
      - name: differ_surcharge_total
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: decimal
  - name: fact_fhvhv_tracking_daily_t
    columns:
      - name: date_id_fk
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
                column_type: string