sources:
  - name: bronze
    database: delta
    schema: bronze
    tables:
      - name: location
        external:
          location: 's3a://nyc-trip-bucket/bronze/location'
          using: delta
        columns:
          - name: location_id
            data_type: int
          - name: borough
            data_type: string
          - name: zone
            data_type: string
          - name: sevice_zone
            data_type: string