apiVersion: v1
kind: Secret
metadata:
  name: spark-env-secret
  namespace: spark
type: Opaque
data:
   PYTHONPATH: L29wdC9hcHA=
   S3_END_POINT: aHR0cDovL21pbmlvLm1pbmlvLnN2Yy5jbHVzdGVyLmxvY2FsOjkwMDA=
   S3_ACCESS_KEY: YWRtaW4=
   S3_SECRET_KEY: YWRtaW4xMjM=
   KAFKA_CONSUMER_SERVER: a2Fma2Eua2Fma2Euc3ZjLmNsdXN0ZXIubG9jYWw6OTA5Mg==
   BUCKET_NAME: bnljLXRyaXAtYnVja2V0
   LOCATION_CSV_PATH: czNhOi8vbnljLXRyaXAtYnVja2V0L255Yy1kYXRhL2xvY2F0aW9uLmNzdg==
   DPC_BASE_NUM_CSV_PATH: czNhOi8vbnljLXRyaXAtYnVja2V0L255Yy1kYXRhL2RwY19iYXNlX251bS5jc3Y=
   
