apiVersion: v1
kind: Secret
metadata:
  name: webhook-secret
  namespace: airflow
type: Opaque
data:
  SLACK_WEB_HOOK: 'aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA3NjA4WEtZREEvQjA3NjhEMU4wM1YvMHF2Qmp4RTVHc0FKbUxkbHhEOVVlQm5R'  # "admin" được mã hóa bằng base64
