name: Publish Docker images

on:
  push:
    branches: ['main']

jobs:
  build_and_push_producer_imane:
    name: Build and Push producer Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata for producer service
        id: meta_service1
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/trip-generator
      
      - name: Build and push producer Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./docker-custom-service/kafka
          push: true
          tags: latest
          labels: ${{ steps.meta_service1.outputs.labels }}
          
  build_and_push_airflow_imane:
    name: Build and Push Airflow Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for airflow service
        id: meta_service2
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/airflow-spark

      - name: Build and push Airflow Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./docker-custom-service/airflow
          push: true
          tags: latest
          labels: ${{ steps.meta_service2.outputs.labels }}
