image:
  tag: 449

additionalCatalogs:
  delta: |
    connector.name=delta_lake
    hive.metastore.uri=thrift://my-hive-metastore:9083
    hive.s3.aws-access-key=admin
    hive.s3.aws-secret-key=admin123
    hive.s3.endpoint=http://minio.minio.svc.cluster.local:9000
    hive.s3.path-style-access=true
    hive.s3.max-connections=1000
    hive.s3.ssl.enabled=false
    delta.register-table-procedure.enabled=true
    delta.enable-non-concurrent-writes=true
additionalRequirements:
  - sqlalchemy-trino

bootstrapScript: |
  #!/bin/bash
  pip install sqlalchemy-trino &&\
  if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi
secretMounts:
  - name: redis-table-schema-volumn
    path: /etc/redis
    secretName: redis-table-definition
server:
  workers: 2
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts: 
    - host:  trino.minhtuyenvp02.id.vn
      paths:
        - path: /
          pathType: ImplementationSpecific
coordinator:
  resources:
    limits:
      cpu: 1
      memory: 3Gi
    requests:
      cpu: 1
      memory: 2Gi
worker:
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 1
      memory: 2Gi
  